name: "Send reviewer reminder"
on:
  schedule:
    # Run every hour
    - cron: "45 1 * * *"

jobs:
  review-reminder:
    permissions:
      pull-requests: write
    if: github.repository == 'pjangam/playground'
    runs-on: ubuntu-latest
    steps:
      - uses: sojusan/github-action-reminder@v1
        with:
          reminder_message: "Please close this PR it is pending for long time"
          inactivity_deadline_hours: 1
          default_users_to_notify: |
            @pjangam
