name: Test dropdown

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        required: true
        description: idv or doc upload, IDV is for instance issuance doc upload for others
        options: 
        - blue
        - green
        - red


jobs:
  add_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print color from iput
        run: |
            echo "from gh"
            echo ${{ github.event.inputs.type }}
            echo "from INPUT_ with double dollar"
            echo $INPUT_type
            if ${{ github.event.inputs.type }} == 'blue';
            then
              echo "you selected red"
            else
              echo "you selected blue"
            fi
            
