name: Test dropdown

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        required: true
        description: idv or doc upload, IDV is for instance issuance doc upload for others
        options: 
        - blue
        - red


jobs:
  add_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create new digram
        run: |
            echo ${{ github.event.inputs.type }}
            echo $INPUT_type
            if ${{ github.event.inputs.type }} == 'blue';
            then
            echo "you selected blue"
            else
            echo "you selected red"
            fi
            
