name: shell test
on:
  workflow_dispatch:
    inputs:
      clientname:
        description: 'client name'
        required: false
jobs:
  test_shell:
    runs-on: ubuntu-latest
    steps:
     
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.10
    
    - uses: haya14busa/action-cond@v1
      id: condval
      with:
        cond: ${{ github.event.inputs.clientname != '' }}
        if_true: echo "client name is set ${{ github.event.inputs.clientname}}"
        if_false: echo "not set"
    - run: |
       uuidgen /
       terraform --version
       echo -n 'dev_endpoint = '
