name: shell test
on:
  workflow_dispatch:
    inputs:
      clientname:
        description: 'client name'
        required: true
jobs:
  test_shell:
    runs-on: ubuntu-latest
    steps:
     
    - uses: haya14busa/action-cond@v1
      id: condval
      with:
        cond: ${{ github.event.inputs.clientname != '' }}
        if_true: "client name is set ${{ github.event.inputs.clientname}}"
        if_false: "not set"
