name: terraform apply

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.10
        terraform_wrapper: false
    
    - uses: actions/checkout@v2
    - name: Configure stage AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-1
    - run: |
        cd terraform
        make deploy -s
